org.gradle.jvmargs = -Xmx2G
org.gradle.parallel = true

java_version = 21
minecraft_version = 1.21.1

# Mod properties
mod_version = 0.2.1
maven_group = soup587
archives_name = jigcompats
enabled_platforms = fabric,neoforge

mod_id = jigcompats
display_name = JigCompats
description = Do stuff you can't with other methods
authors = soup587

# Dependencies
fabric_loader_version = 0.16.10
fabric_api_version = 0.115.1+1.21.1
neoforge_version = 21.1.125

figura_version = 0.1.5+1.21.1

create_version = 6.0.0-9
flywheel_version = 1.0.0-10
ponder_version = 1.0.42

# Libraries
luaj = 3.0.8
nv_websocket = 2.14

registrate = MC1.21-1.3.0+62